# Generated by Django 5.1.2 on 2024-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumelinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
