# Generated by Django 5.1.2 on 2024-12-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumelinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttype',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='reporttype',
            name='created',
        ),
    ]
