# Generated by Django 5.1.2 on 2024-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumelinkapp', '0002_alter_reporttype_options_remove_reporttype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
