from .settings_view import SettingView
from .account_manage_view import AccountManageView
from .contact_view import ContactView
from .notification_view import NotificationView
from .community_guidelines import CommunityGuidelinesView
from .delete_user_view import delete_user
from .password_view import ChangePasswordView
from .about_us_view import AboutUsView
from .filter_content_view import FilterContentUpdateView